GPSTracker/urls.py
__author__ = 'matt'
from django.conf.urls import patterns, url

urlpatterns = patterns('GPSTracker.views',
    # Index
    url(r'^$', 'index'),
    # Root of the client based views
    url(r'^clients/$', 'clients'),
    # About
    url(r'^about/$', 'about'),
    # Group View
    url(r'^groups/(?P<client_id>\d+)/$', 'group'),
    # Group Detail View
    url(r'^groups/detail/(?P<group_id>\d+)/$', 'group_detail'),
    # GeoJSON/KML Individual View
    url(r'^(?P<geom_format>\w+)/(?P<geom_type>\w+)/(?P<feat_id>\d+)/$', 'geom_export'),
    # GeoJSON/KML Group Geometry URLs, note we're passing the additional 'group' dictionary value
    # to the view function.
    url(r'^(?P<geom_format>\w+)/(?P<geom_type>\w+)/group/(?P<feat_id>\d+)/$', 'geom_export', {'group':True}),
    ## UPLOAD FILES
    url(r'^uploadfile/$', 'uploadfile1'),
    url(r'^uploadfile/2/$', 'uploadfile2'),
    url(r'^uploadfile/success/$', 'upload_success'),
)

PntTrax/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.gis import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^gpstracker/', include('GPSTracker.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # Auth related URLs
    (r'^accounts/login', 'django.contrib.auth.views.login', {'template_name':'../templates/registration/login.html'}),
    (r'^accounts/logout', 'django.contrib.auth.views.logout'),
)

GPSTracker/models.py
import datetime
from django.contrib.gis.db import models
# Import Auth app's group mode. Alias to avoid conflicts with GPSTracker app.
# from django.contrib.auth.models import Group as AuthGroup
from django.contrib.auth.models import AbstractUser

class Client(models.Model):
    """Information regarding the client"""
    name = models.CharField('Name', max_length=255, unique=True)
    city = models.CharField('City', max_length=255)
    state = models.CharField('State', max_length=255)

    def __unicode__(self):
        return self.name

class GPSUser(AbstractUser):
    job_title = models.CharField('Job Title', max_length=255, blank=True)
    authorized_clients = models.ManyToManyField(Client)

class Group(models.Model):
    """A high-level container for related GPS locations."""
    name = models.CharField('Name',max_length=255,default='Unknown Group')
    client = models.ForeignKey(Client)
    pathway = models.CharField('File Pathway', max_length=500, blank=True)
    comment = models.CharField('Comment',max_length=255, blank=True)

    def __unicode__(self):
        return self.name

class FeaturePurpose(models.Model):
    """Different Purposes for GPS Feature. E.g. Photo Point, Sample Location."""
    purpose = models.CharField('Purpose', max_length=255,default='Unknown')

    def __unicode__(self):
        return self.purpose

def get_FeaturePurpose():
    """Used to set default FK value."""
    return FeaturePurpose.objects.get(purpose='Unknown')

class CollectionMethod(models.Model):
    """How was the feature collected? Trimble, Phone, Digitized?"""
    method = models.CharField('Collection Method', max_length=255,default='Unknown')

    def __unicode__(self):
        return self.method

def get_CollectionMethod():
    """Used to set default FK value."""
    return CollectionMethod.objects.get(method='Unknown')

class geomBase(models.Model):
    """Abstract base class for geometry tables."""
    name = models.CharField('Name',max_length=255, blank=True, default='Default Name')
    collectDate = models.DateField('Collection Date', blank=True, default=datetime.date(1901,1,1))
    collectTime = models.TimeField('Collection Time', blank=True, default=datetime.time(12,12,12))
    addDate = models.DateField('Add Date', auto_now_add=True)
    updateDate = models.DateField('Update Date', auto_now=True)
    comment = models.CharField('Comment',max_length=255, blank=True, default='')
    group = models.ForeignKey(Group)
    featurePurpose = models.ForeignKey(FeaturePurpose, default=get_FeaturePurpose)
    collectionMethod = models.ForeignKey(CollectionMethod, default=get_CollectionMethod)

    objects = models.GeoManager()

    def __unicode__(self):
        return self.name

    class Meta:
        abstract = True

class Point(geomBase):
    """Point Features"""
    lon = models.FloatField('Lon', blank=True, default=float(0))
    lat = models.FloatField('Lat', blank=True, default=float(0))

    geom = models.PointField('Point Geom')

class Line(geomBase):
    """Line Features"""
    geom = models.LineStringField('Line Geom')

class Poly(geomBase):
    """Polygon Features"""
    geom = models.PolygonField('Poly Geom')

GPSTracker/forms.py
__author__ = 'matt'
from fiona import collection
from django import forms
from django.core.exceptions import ValidationError
from .models import Group
import zipfile

def validate_shp(value):
    """
    Raises validation errors for an uploaded file in the following cases:
    * not a zip.
    * zip, but no shp.
    * zip, but multiple shp.
    * no PRJ file.
    * non-WGS84 PRJ File.

    Parses in-memory zipfile for filenames.
    """

    """Raise ValidationError if input is not a zip file."""
    if value.name[len(value.name)-3:].lower() <> 'zip':
        raise ValidationError(u'File Error: Not a valid .zip file.')

    filenames = zipfile.ZipFile(value).namelist()
    # Create a list of files ending in 'shp'
    shpFiles = [file for file in filenames if file[len(file)-3:] == 'shp']
    if len(shpFiles) == 0:
        raise ValidationError(u'File Error: No shapefile detected in zip.')
    elif len(shpFiles) > 1:
        raise ValidationError(u'File Error: Multiple shapefiles detected in zip.')
    # Create a list of projection files.
    prjFile = [file for file in filenames if file[len(file)-3:] == 'prj']
    if len(prjFile) == 0:
        raise ValidationError(u'File Error: No projection file detected.')
    # Use zipfile class' read method to check the contents of a prj file to verify WGS84
    if 'GCS_WGS_1984' not in zipfile.ZipFile(value).read(prjFile[0]):
        raise ValidationError(u'File Error: File does not appear to be in WGS84 GCS.')


def get_groups():
    """Return groups for a choice list"""
    group_list = Group.objects.all()
    group_choice = []
    for group in group_list:
        group_choice.append((group.id, group.name))
    return group_choice

def get_shpFields(shpPath):
    """Return a list of tuples denoting fields for a given shapefile.
    You need tuples for a choice field: https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.Field.choices"""
    shpIn = collection(shpPath, "r")
    attributes = shpIn.schema['properties'].keys()
    attZip = zip(attributes,attributes)
    attZip.append((u'','None'))
    # use zip to create a list of tuples.
    # TODO: Need to add a None value or something for optional fields.
    return attZip

class uploadFileForm1(forms.Form):
    """
    First file upload form page. Take uploaded file from user and
    associate with a given GPS Group.
    """

    # https://docs.djangoproject.com/en/dev/ref/forms/api/#styling-required-or-erroneous-form-rows
    error_css_class = 'text-error'
    required_css_class = 'text-required'

    file = forms.FileField('File', validators=[validate_shp])

class uploadFileForm2(forms.Form):
    """
    Grab an uploaded file and all manual mappings provided by a user
    """
    def __init__(self, *args, **kwargs):
        # http://stackoverflow.com/questions/987237/adding-a-kwarg-to-a-class
        self.shpPath = kwargs.pop('shpPath', None)
        super(uploadFileForm2, self).__init__(*args, **kwargs)
        self.attributeChoices = get_shpFields(self.shpPath)
        self.fields['group'] = forms.ChoiceField(choices=get_groups(), label='GPS Group')
        self.fields['name'] = forms.ChoiceField(choices=self.attributeChoices, label='Name')
        self.fields['type'] = forms.ChoiceField(choices=self.attributeChoices, required=False, label='Feature Type')
        self.fields['method'] = forms.ChoiceField(choices=self.attributeChoices, required=False, label='Collection Method')
        self.fields['collectDate'] = forms.ChoiceField(choices=self.attributeChoices, required=False, label='Collection Date')
        self.fields['collectTime'] = forms.ChoiceField(choices=self.attributeChoices, required=False, label='Collection Time')
        self.fields['comment'] = forms.ChoiceField(choices=self.attributeChoices, required=False, label='Comment')

    # https://docs.djangoproject.com/en/dev/ref/forms/api/#styling-required-or-erroneous-form-rows
    error_css_class = 'text-error'
    required_css_class = 'text-required'

GPSTracker/views.py
# Create your views here.
import logging, os
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import Context, RequestContext, loader
from django.shortcuts import render_to_response
from .forms import uploadFileForm1, uploadFileForm2
from .models import Client, Group, Point, Line, Poly
from GPSTracker.file_uploads import ShpUploader

# Project Shortcuts
from shortcuts import djangoToExportFormat

logger = logging.getLogger(__name__)

def index(request):
    return render_to_response('gpstracker/index.html',{},context_instance=RequestContext(request))

def about(request):
    return render_to_response('gpstracker/about.html',{},context_instance=RequestContext(request))

@login_required
def clients(request):
    """Return a list of clients."""
    if request.user.is_staff:
        # Staff can view all clients.
        client_list = Client.objects.all()
        gps_group_list = Group.objects.all()
    else:
        # Filter clients and GPS Groups based on a user's group
        client_list = Client.objects.filter(gpsuser=request.user)
        # Group list filtered by client_list
        gps_group_list = Group.objects.filter(client__name__in=client_list)

    return render_to_response('gpstracker/clients.html', {'client_list': client_list, 'group_list': gps_group_list}, context_instance=RequestContext(request))

@login_required
def group(request, client_id):
    """Returns the GPS groups related to the selected client"""
    # If a user is staff, they can view all clients.
    # If not, get a list of clients that a user is associated with.
    # Compare that to the client object retrieved via Client.objects.get(pk=client_id)
    if request.user.is_staff or Client.objects.get(pk=client_id) in Client.objects.filter(gpsuser=request.user):
        client_selected = Client.objects.get(pk=client_id)
        group_list = Group.objects.filter(client__pk=client_id)
        return render_to_response('gpstracker/group.html', {'client_selected': client_selected, 'group_list': group_list}, context_instance=RequestContext(request))
    else:
        response = render_to_response('gpstracker/unauthorized.html', context_instance=RequestContext(request))
        response.status_code = 403
        return response

@login_required
def group_detail(request, group_id):
    """Return a list of GPS Features for a GPS Group."""
    # Using a group_id, get the corresponding client object.
    # Check if a user is authorized to view data for that client.
    if request.user.is_staff or Client.objects.get(group__pk=group_id) in Client.objects.filter(gpsuser=request.user):
        args = dict()
        args['group'] = Group.objects.get(pk=group_id)
        point_list = Point.objects.filter(group__pk = group_id)
        line_list = Line.objects.filter(group__pk = group_id)
        poly_list = Poly.objects.filter(group__pk = group_id)
        geom_dict = {'point_list':point_list,'line_list':line_list,'poly_list':poly_list}
        # Only send to render_to_response those geoms (point/line/poly) that exist
        for geom_key, geom_value in geom_dict.iteritems():
            if geom_value.exists():
                args[geom_key] = geom_value
        return render_to_response('gpstracker/group_detail.html', args, context_instance=RequestContext(request))
    else:
        response = render_to_response('gpstracker/unauthorized.html', context_instance=RequestContext(request))
        response.status_code = 403
        return response

@login_required
def geom_export(request, feat_id, geom_type, geom_format, group=False):
    """Return a serialized representation of geom and properties from a Django GeoQuerySet"""
    ## Grab appropriate model
    modelMap = {'point':(Point, 'group__point__pk'),'line':(Line, 'group__line__pk'),'poly':(Poly, 'group__poly__pk')}
    if geom_type.lower() in modelMap.keys():
        # Test if we're dealing with a geom group, or a individual geom
        if group and (request.user.is_staff or Client.objects.get(group__pk=feat_id) in Client.objects.filter(gpsuser=request.user)):
            geom_rep = modelMap[geom_type][0].objects.filter(group__pk=feat_id)
        # Using keyword argument dictionary allows keyword parameters to be dynamicallys set.
        elif not group and (request.user.is_staff or Client.objects.get(**{modelMap[geom_type][1]:feat_id}) in Client.objects.filter(gpsuser=request.user)):
            geom_rep = modelMap[geom_type][0].objects.filter(pk=feat_id)
        else:
            response = HttpResponse('{WARNING: Unauthorized Resource Requested.}', content_type="text/plain")
            response.status_code = 403
            return response

    response = djangoToExportFormat(request, geom_rep, format=geom_format)
    return response

@login_required
def uploadfile1(request):
    """
    Present user with file upload screen...
    if successful, send them to a second form page to begin field mapping.
    if unsuccessful, have them retry.
    """
    if request.user.is_staff:
        if request.method == 'POST':
            logger.info('User %s Began Upload of File %s' % (request.user.username, request.FILES['file']))
            form = uploadFileForm1(request.POST, request.FILES)
            if form.is_valid():
                # form.cleaned_data contains an in memory version of the uploaded file.
                uploaded_shp = ShpUploader(form.cleaned_data['file'])
                # Store ShpUploader instance in cookie to be referenced
                # in second upload form.
                request.session['uploaded_shp'] = uploaded_shp
                return HttpResponseRedirect(reverse('GPSTracker.views.uploadfile2'))
            else:
                for uploadfile_error in form.errors['file']:
                    logger.warning(uploadfile_error)
        else:
            form = uploadFileForm1()
        return render_to_response('gpstracker/uploadfile1.html', {'form': form}, context_instance=RequestContext(request))
    else:
        response = render_to_response('gpstracker/unauthorized.html', context_instance=RequestContext(request))
        response.status_code = 403
        return response

@login_required
def uploadfile2(request):
    """
    Associate fields from a successfully parsed SHP with model fields.
    """
    if request.user.is_staff:
        if request.method == 'POST':
            # Required to repass shpPath kwarg
            form = uploadFileForm2(request.POST,shpPath=request.session['uploaded_shp'].upload_full_path)
            if form.is_valid():
                # Pass user-defined field mappings to import_shapefile method.
                request.session['uploaded_shp'].import_shapefile(form.cleaned_data)
                logger.info('Successful - User %s Uploaded File %s' % (request.user.username, request.session['uploaded_shp'].upload_full_path))
                return HttpResponseRedirect(reverse('GPSTracker.views.upload_success'))
            else:
                print form.errors
        else:
            form = uploadFileForm2(shpPath=request.session['uploaded_shp'].upload_full_path)
        return render_to_response('gpstracker/uploadfile2.html', {'form': form} ,context_instance=RequestContext(request))
    else:
        response = render_to_response('gpstracker/unauthorized.html', context_instance=RequestContext(request))
        response.status_code = 403
        return response

@login_required
def upload_success(request):
    """
    A file a has been successfully upload and processed into an appropriate model.
    """
    return render_to_response('gpstracker/upload_success.html', context_instance=RequestContext(request))

templates/gpstracker/about.html
{% extends "base.html" %}

{% block title %}Homepage{% endblock %}

{% block content %}
<div class="row">
    <div class="span12">
        <h3>About</h3>
        <p>Source code for this site can be found at: <a href="https://github.com/mattmakesmaps/PntTrax">https://github.com/mattmakesmaps/PntTrax</a></p>
        <p>Some of the technologies that power this site <strong>include:</strong></p>
    </div>
</div>
<div class="row">
    <div class="span4">
        <h4>Fiona</h4>
        <p>Used to parse uploaded shapefiles, presenting a user with fields to map against database tables.</p>
    </div>
    <div class="span4">
        <h4>GeoDjango</h4>
        <p>A web framework used as the foundation this application.</p>
    </div>
    <div class="span4">
        <h4>Icons</h4>
        <p>Icons provided by the awesome Project Noun (CC-BY-SA).</p>
    </div>
</div>
<div class="row">
    <div class="span4">
        <h4>Leaflet</h4>
        <p>Provides client-side mapping functionality.</p>
    </div>
    <div class="span4">
        <h4>PostGIS/Spatialite</h4>
        <p>The underlying spatial RDBMS.</p>
    </div>
    <div class="span4">
        <h4>Twitter Bootstrap</h4>
        <p>The base styling for all elements in this page. A non-default bootstrap theme is being hosted via the
        <a href="http://www.bootstrapcdn.com/">BootstrapCDN</a>.</p>
    </div>
</div>
<div class="row">
    <div class="span4">
        <h4>Vectorformats</h4>
        <p>Created by Chris Schmidt, this library is used to provide basic conversion between Django QuerySets to output formats such as GeoJSON and KML. Accessible via service URL endpoints.</p>
    </div>
</div>
{% endblock %}

templates/gpstracker/clients.html
{% extends "base.html" %}

{% block title %}Clients{% endblock %}

{% block content %}
    <h3>Clients</h3>
    {# NOTE: Model name is in 'lowercase' #}
    {% if user.is_staff %}
        <a href="{% url 'admin:GPSTracker_client_add' %}">Add Client</a>
    {% endif %}
    <div class="row">
        <div class="span12">
            {% if client_list %}
                {% for c in client_list %}
                    <h4><a href="{% url 'GPSTracker.views.group' c.id %}">{{ c.name }}</a></h4>
                    <h5 class="muted">{{ c.city }}, {{ c.state }}</h5>
                    <ul>
                        <!-- https://docs.djangoproject.com/en/dev/topics/templates/#accessing-method-calls -->
                            <li>Associated GPS Groups: {{ c.group_set.all|length }}</li>
                    </ul>
                {% endfor %}
            {% else %}
                    <span class="label label-important">Whoops!</span> Your account isn't associated with any clients.
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/gpstracker/group.html
{% extends "base.html" %}

{% block title %}GPS Groups{% endblock %}

{% block content %}
    <h3>GPS Groups</h3>
    {% if user.is_staff %}
        <a href="{% url 'admin:GPSTracker_group_add' %}">Add GPS Group</a>
    {% endif %}
    <div class="row">
        <div class="span12">
            {% if client_selected %}
                <h4>{{ client_selected.name }}</h4>
                <h5 class="muted">{{ client_selected.city }}, {{ client_selected.state }}</h5>
                <ul>
                    <!-- https://docs.djangoproject.com/en/dev/topics/templates/#accessing-method-calls -->
                    {% for group in client_selected.group_set.all %}
                        <li><a href="{%  url 'GPSTracker.views.group_detail' group.id %}">{{ group.name }}</a> - {{ group.comment }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No GPS Groups. How about adding one?</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/gpstracker/group_detail.html
{% extends "base.html" %}

{% block title %}{{ group.name }} Detailed Report{% endblock %}

{% block content %}
    <h3>{{ group.name }} Locations</h3>
    <p class="muted">{{ group.comment }}</p>

    {# leaflet map #}
    <div id="map"></div>
    <h4>Points {% if point_list %}<a href="../../../kml/point/group/{{ group.id }}" class="muted">(KML Download)</a> <a href="../../../shp/point/group/{{ group.id }}" class="muted">(Shapefile Download)</a>{% endif %} </h4>

    {% if point_list %}
        <table id="point_table" class="table table-hover table-striped table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Method</th>
                <th>Date</th>
                <th>Comment</th>
            </tr>
            </thead>
            <tbody>
            {% for p in point_list %}
                <tr id={{ p.id }}>
                    <td>{{ p.name }}</td>
                    <td>{{ p.featurePurpose }}</td>
                    <td>{{ p.collectionMethod }}</td>
                    <td>{{ p.collectDate }}</td>
                    <td>{{ p.comment }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="text-error">No Points</p>
    {% endif %}

    <h4>Lines {% if line_list %}<a href="../../../kml/line/group/{{ group.id }}" class="muted">(KML Download)</a> <a href="../../../shp/line/group/{{ group.id }}" class="muted">(Shapefile Download)</a>{% endif %} </h4>
    {% if line_list %}
        <table id="line_table" class="table table-hover table-striped table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Method</th>
                <th>Date</th>
                <th>Comment</th>
            </tr>
            </thead>
            <tbody>
            {% for l in line_list %}
                <tr id={{ l.id }}>
                    <td>{{ l.name }}</td>
                    <td>{{ l.featurePurpose }}</td>
                    <td>{{ l.collectionMethod }}</td>
                    <td>{{ l.collectDate }}</td>
                    <td>{{ l.comment }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="text-error">No Line Features</p>
    {% endif %}


    <h4>Polygons {% if poly_list %}<a href="../../../kml/poly/group/{{ group.id }}" class="muted">(KML Download)</a> <a href="../../../shp/poly/group/{{ group.id }}" class="muted">(Shapefile Download)</a>{% endif %} </h4>
    {% if poly_list %}
        <table id="poly_table" class="table table-hover table-striped table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Method</th>
                <th>Date</th>
                <th>Comment</th>
            </tr>
            </thead>
            <tbody>
            {% for p in poly_list %}
                <tr id={{ p.id }}>
                    <td>{{ p.name }}</td>
                    <td>{{ p.featurePurpose }}</td>
                    <td>{{ p.collectionMethod }}</td>
                    <td>{{ p.collectDate }}</td>
                    <td>{{ p.comment }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="text-error">No Polygon Features</p>
    {% endif %}
{% endblock %}
{% block extrascript %}
<script type="text/javascript">
    {# Add group ID, to be used for GeoJSON URLs in group_mapcode.js #}
    var group_id = {{ group.id }};
    {# Add success/fail toggles, to be used in group_mapcode.js #}
    {% if point_list %}
        var point_success = true;
    {% else %}
        var point_success = false;
    {% endif %}

    {% if line_list %}
        var line_success = true;
    {% else %}
        var line_success = false;
    {% endif %}

    {% if poly_list %}
        var poly_success = true;
    {% else %}
        var poly_success = false;
    {% endif %}
</script>
<script src="{{ STATIC_URL }}js/Bing.js"></script>
<script src="{{ STATIC_URL }}js/group_mapcode.js"></script>
{% endblock %}

templates/gpstracker/index.html
{% extends "base.html" %}

{% block title %}Homepage{% endblock %}

{% block content %}
<div class="row">
    <div class="span12">
        <h1>RIDOLFI GPS Tracker</h1>
    </div>
</div>
<div class="row">
    <div class="span4">
        <img src="{{ STATIC_URL }}img/gps225.png">
    </div>
    <div class="span4">
        <img src="{{ STATIC_URL }}img/map225.png">
    </div>
    <div class="span4">
        <img src="{{ STATIC_URL }}img/notebook225.png">
    </div>
</div>
<div class="row">
    <div class="span12">
        <p>This site serves as a repository for finalized GPS datasets, suitable for
            transmittal to the client. GPS datasets have been augmented to include supplementary
            information from sources such as field notes or aerial image markups. Care has been
            taken to identify the source for each feature, GPS collected or otherwise.</p>
    </div>
</div>
{% endblock %}

templates/gpstracker/unauthorized.html
{% extends "base.html" %}

{% block title %}Unauthorized Resource{% endblock %}

{% block content %}
<div class="row">
    <div class="span12">
        <h3>Unauthorized Resource Requested</h3>
        <p><span class="label label-important">WARNING</span>
        The currently logged in account is not authorized to view the requested content.</p>
    </div>
</div>
{% endblock %}

templates/gpstracker/upload_success.html
{% extends "base.html" %}

{% block title %}Upload Success{% endblock %}

{% block content %}
    <h3>Dataset Upload: Success</h3>
    <div class="row">
        <div class="span12">
            <p><b>Hooray!</b> Your dataset has been uploaded to the server.</p>
            <p>Go to the <a href="/gpstracker/clients/">clients</a> page to view them.</p>
            <p>Use the <a href="/admin/">admin</a> interface to edit individual features.</p>
        </div>
    </div>
{% endblock %}

templates/gpstracker/uploadfile1.html
{% extends "base.html" %}

{% block title %}Dataset Upload{% endblock %}

{% block content %}
<div class="row">
    <div class="span12">
        <h3>Dataset Upload: Step 1</h3>
        <p>Select a compressed shapefile (.shp) to upload.</p>
        <p>Current Limitations:</p>
        <ul>
            <li>Shapefile must be in WGS84 GCS.</li>
            <li>Timestamps must be in the format of HH:MM[:SS]. Both 12- and 24-hour formats acceptable.</li>
        </ul>
    </div>
    <div class="span12">
        <table>
            <form enctype="multipart/form-data" action="." method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-small btn-primary" type="button" value="Submit" />
            </form>
        </table>
    </div>
</div>
{% endblock %}

templates/gpstracker/uploadfile2.html
{% extends "base.html" %}

{% block title %}Dataset Upload{% endblock %}

{% block content %}
<div class="row">
    <div class="span12">
        <h3>Dataset Upload: Step 2</h3>
        <p>Assign shapefile field names to database field names.</p>
        <p>Select 'NONE' to use a default value.</p>
        <p>Current Limitations:</p>
        <ul>
            <li>Shapefile must be in WGS84 GCS.</li>
            <li>Timestamps must be in the format of HH:MM[:SS]. Both 12- and 24-hour formats acceptable.</li>
        </ul>
    </div>
    <div class="span12">
        <table>
            <form enctype="multipart/form-data" action="{% url 'GPSTracker.views.uploadfile2' %}" method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-small btn-primary" type="button" value="Submit" />
            </form>
        </table>
    </div>
</div>
{% endblock %}